mutation {
  register(
    data: {
    firstName: "Inna", 
    lastName: "Losev", 
    email: "i515@ev.de", 
    name: "il", 
    password: "12345", 
    role: "ADMIN"}) 
  {
    firstName
    lastName
    email
    name
    role
  }
}
,
mutation {
  register( 
    data: {
    firstName: "Leon", 
    lastName: "Meister",
    name: "lmeister",
    email: "lm@dev.de", 
    password: "23456", 
    role: "USER"}) 
  {
    firstName,
    lastName,
    email,
    name,
    role
    }
  },
mutation {
  register(
    data: {
      firstName: "Rene", 
      lastName: "Springer", 
      name: "rspringer", 
      password: "12345", 
      email: "rs@wrk.com", 
      role: "GUEST"}) {
    name
    firstName
    lastName
    email
    role
  }
}
