mutation {
  register(
    firstName: "Inna", 
    lastName: "Losev", 
    email: "i515@ev.de", 
    name: "il", 
    password: "12345", 
    role: "ADMIN") {
    firstName
    lastName
    email
    name
    role
  }
}
,
mutation {
  register(
    firstName: "Leon", 
    lastName: "Meister", 
    email: "lm@dev.de", 
    name: "lmeister", 
    password: "23456", 
    role: "USER") {
    firstName,
    lastName,
    email,
    name,
    role
  }
},
mutation {
  register(
    firstName: "Rene", 
    lastName: "Springer", 
    email: "rs@dev.de", 
    name: "rspringer", 
    password: "34567", 
    role: "GUEST") {
    firstName,
    lastName,
    email,
    name,
    role
  }
}